# Generated by Django 5.1.1 on 2024-09-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='numero_apartamento',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='matricula',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
